// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4PknULI8WfzvYVoAKbOrpfHOKzQ3ASO8',
    appId: '1:943512550950:web:141637cf40f344cf4ef0e7',
    messagingSenderId: '943512550950',
    projectId: 'solomons-school',
    authDomain: 'solomons-school.firebaseapp.com',
    storageBucket: 'solomons-school.firebasestorage.app',
    measurementId: 'G-VMR2B03JQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQVUEu9NHIN7d8jhzAdxFnROXejVTWXZs',
    appId: '1:943512550950:android:0c49f68cafb7392b4ef0e7',
    messagingSenderId: '943512550950',
    projectId: 'solomons-school',
    storageBucket: 'solomons-school.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzinfGEg1BCpGmqumpy5UkLDb4e7VfHSU',
    appId: '1:943512550950:ios:256644ac680c28644ef0e7',
    messagingSenderId: '943512550950',
    projectId: 'solomons-school',
    storageBucket: 'solomons-school.firebasestorage.app',
    iosClientId: '943512550950-g4nsq8cdnp824oginofcbihvllmd31uj.apps.googleusercontent.com',
    iosBundleId: 'com.school.solomon.solomonSchoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzinfGEg1BCpGmqumpy5UkLDb4e7VfHSU',
    appId: '1:943512550950:ios:256644ac680c28644ef0e7',
    messagingSenderId: '943512550950',
    projectId: 'solomons-school',
    storageBucket: 'solomons-school.firebasestorage.app',
    iosClientId: '943512550950-g4nsq8cdnp824oginofcbihvllmd31uj.apps.googleusercontent.com',
    iosBundleId: 'com.school.solomon.solomonSchoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4PknULI8WfzvYVoAKbOrpfHOKzQ3ASO8',
    appId: '1:943512550950:web:4eab29eb5f04ece24ef0e7',
    messagingSenderId: '943512550950',
    projectId: 'solomons-school',
    authDomain: 'solomons-school.firebaseapp.com',
    storageBucket: 'solomons-school.firebasestorage.app',
    measurementId: 'G-91CMKC0TF4',
  );
}
